apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1dev
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0002-tenant/tkrw-pr714-0075-0002-app/devfile-sample-1dev@sha256:f603b2ce547f6ce77f19795ce0fda71f39522b657bc259ece93d0eff153da51f
        name: my-nodejs
        resources: {}
status: {}
